```{r setup, include=FALSE}

####################
####################
##MODEL DEFINITION##
####################
####################

source("~/../Dropbox/Grind/grind.r")                     # grind.r made by R.J. de Boer: 
library(tidyverse)                   # libraries inclusions (installed with install.packages("name"))
library(ggplot2)
library(grid)


BELOW IS THE ODE-MODEL DEFINITION AS USED IN THE MAIN TEXT:
model <- function(t, state, parms) {
  with(as.list(c(state,parms)), {

    phi <- (1+b-c*h)*C + (1-c*h)*N
    dC <- (1+b-c*h)*C - l*C + h*N*C - phi*C
    dN <- (1-c*h)*N + l*C - h*N*C - phi*N

    return(list(c(dC, dN)))
  })
}

``` 

```{r Gene classes, echo=FALSE}
###########################################################
### MAKING A PLOT WITH ALL THE GENE CLASSES IN MODEL 1 ####
###########################################################
alldat<-data.frame()   # creates emtpy data frame

c = 0.3
l = 0.02

bvals = c(-0.01,0.0,0.005,0.01,0.02,0.04,0.08)
hvals = seq(0.0000,0.05,by=0.001)

for(bloop in bvals) # loop over values of b
{
    for(hloop in hvals) # loop over values of h
    {
      p <- c(h=hloop, l=l, c=c, b=bloop)     # p is a named vector of parameters
      s <- c(C=0.999,N=0.1)                    # s is the intial state vector
      f<- newton()                           # find equilibrium (using the Newton-Raphson method)
      cnow=f["C"]                            # store found C
      nnow=f["N"]                            # store found N         
      phi <- (1+bloop-c*hloop)*cnow + (1-c*hloop)*nnow                    # calculate get phi for this iteration
      phi_alt <- (1+bloop-c*hloop*nnow)*cnow + (1-c*hloop*cnow)*nnow      # phi for alternative costs (per interaction)
      phi_alt2 <- (1+bloop-c*hloop*cnow)*cnow + (1-c*hloop*cnow)*nnow      # phi for alternative costs (per interaction)
      out <- cbind(C=cnow,N=nnow,h=hloop,b=as.numeric(bloop),phi=phi,phi_alt=phi_alt,phi_alt2=phi_alt2)
      alldat <- rbind(alldat,out)
    }
}
  
# Plot all the data. Will give the 5 gene classes (also with the alt_model). 
main <- alldat %>%
  ggplot(aes(grp=b,x=h,y=phi)) +
  ggtitle("Categories for model from main text (cost = c*h)")+
  geom_line(aes(col=as.factor(b)),size=1.5)+
  geom_hline(yintercept = 1)+
  facet_wrap(~b,nrow=1)+
  theme_bw()    

alt1 <- alldat %>%
  ggplot(aes(grp=b,x=h,y=phi_alt)) +
  ggtitle("Categories (unrescuable or rescuable genes) for cost at interaction (cost = c*h*[other]")+
  geom_line(aes(col=as.factor(b)),size=1.5)+
  geom_hline(yintercept = 1)+
  facet_wrap(~b,nrow=1)+
  theme_bw() 

alt2 <- alldat %>%
  ggplot(aes(grp=b,x=h,y=phi_alt2)) +
  ggtitle("Categories assuming cost scale with amount of donor DNA (cost = c*h*Donor)")+
  geom_line(aes(col=as.factor(b)),size=1.5)+
  geom_hline(yintercept = 1)+
  facet_wrap(~b,nrow=1)+
  theme_bw() 

grid.arrange(main,alt2,alt1) 

  
```

